Unique-AG/ai

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/chat/schemas.py
- unique_toolkit/unique_toolkit/content/service.py
- debug_info is None for assistant messages
> fix: correct ChatMessage schema

- unique_sdk/unique_sdk/api_resources/_chat_completion.py
- unique_toolkit/CHANGELOG.md
- unique_toolkit/poetry.lock
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/language_model/test_language_models_schemas.py
- unique_toolkit/tests/language_model/test_language_models_service_integration.py
- unique_toolkit/tests/language_model/test_language_models_service_unit.py
- unique_toolkit/tests/pytest.ini
- unique_toolkit/unique_toolkit/language_model/schemas.py
- unique_toolkit/unique_toolkit/language_model/service.py
> fix(ai-modules): Add schema compatibilty to support tool calling functionnalities

- unique_sdk/CHANGELOG.md
- unique_sdk/pyproject.toml
- unique_sdk/unique_sdk/api_resources/_content.py
- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/content/test_content_service_integration.py
- unique_toolkit/tests/content/test_content_service_unit.py
- unique_toolkit/unique_toolkit/content/service.py
> feat: Enabling the possibility to upload documents without triggering ingestion

- unique_toolkit/CHANGELOG.md
- unique_toolkit/poetry.lock
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/content/test_content_service_unit.py
- unique_toolkit/tests/test_obj_factory.py
- unique_toolkit/unique_toolkit/content/service.py
> feat(toolkit): content_ids and metadata_filter

- unique_sdk/CHANGELOG.md
- unique_sdk/README.md
- unique_sdk/pyproject.toml
- unique_sdk/unique_sdk/api_resources/_message_assessment.py
- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/chat/test_chat_service_unit.py
- unique_toolkit/unique_toolkit/chat/schemas.py
- unique_toolkit/unique_toolkit/chat/service.py
> feat(ai): message assessment title and label changes

- unique_sdk/CHANGELOG.md
- unique_sdk/pyproject.toml
- unique_sdk/tests/test_api_resource.py
- unique_sdk/tests/test_util.py
- unique_sdk/unique_sdk/_api_requestor.py
- unique_sdk/unique_sdk/_util.py
> chore(ai-module): fix pictet issues with the error

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/content/test_content_service_unit.py
- unique_toolkit/unique_toolkit/content/service.py
- **fix(ai-toolkit): Content's search_content_chunks and search_content_chunks_async**
- **fix(ai-toolkit): Content's search_content_chunks and search_content_chunks_async**
> fix(ai-toolkit): modify search_content_chunks and search_content_chunks

- unique_sdk/CHANGELOG.md
- unique_sdk/pyproject.toml
> chore(sdk): define programming language classifiers explicitly

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/language_model/test_language_model_infos.py
- unique_toolkit/unique_toolkit/language_model/infos.py
> chore(model): deprovision o1-preview and o1-mini

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/language_model/test_language_model_infos.py
- unique_toolkit/unique_toolkit/language_model/infos.py
> feat(ai-models): add GPT 4o V 2024-11-20 as part of the models

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/language_model/test_language_model_infos.py
- unique_toolkit/unique_toolkit/language_model/infos.py
> chore(ai-model): add gpt-4.1 to toolkit

- unique_sdk/CHANGELOG.md
- unique_sdk/README.md
- unique_sdk/examples/custom-assistant/custom_assistant/app.py
- unique_sdk/pyproject.toml
- unique_sdk/unique_sdk/api_resources/_search.py
refs
https://unique-ch.atlassian.net/browse/UN-10850
> fix(sdk): optional chatId

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/language_model/test_language_model_infos.py
- unique_toolkit/unique_toolkit/language_model/infos.py
> feat(ai-modules): add o3 and o4-mini as part of the language model

- examples/tutorials/poetry.lock
- examples/tutorials/pyproject.toml
- examples/tutorials/sdk_examples/folder_udpates.py
- unique_sdk/CHANGELOG.md
- unique_sdk/README.md
- unique_sdk/pyproject.toml
- unique_sdk/unique_sdk/__init__.py
- unique_sdk/unique_sdk/api_resources/_folder.py
- unique_toolkit/poetry.lock
> feat(sdk): update folder properties

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/chat/schemas.py
> feat(toolkit): Introduce ChatMessage Reference on schema

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/language_model/infos.py
> fix(ai-modules): add encoder for AZURE_GPT_4o_2024_1120 to fix tests

- .github/workflows/chore_linting_ruff.yaml
- tutorials/self-host/aks/0-plan/readme.md
- tutorials/self-host/aks/1-code/market_vendor/.dev.env.enc
- tutorials/self-host/aks/1-code/market_vendor/.flaskenv
- tutorials/self-host/aks/1-code/market_vendor/deployment-values/_all.yaml
- tutorials/self-host/aks/1-code/market_vendor/entrypoint.sh
- tutorials/self-host/aks/1-code/market_vendor/market_vendor/__init__.py
- tutorials/self-host/aks/1-code/market_vendor/market_vendor/app.py
- tutorials/self-host/aks/1-code/market_vendor/market_vendor/config.py
- tutorials/self-host/aks/1-code/market_vendor/market_vendor/utils.py
- tutorials/self-host/aks/1-code/market_vendor/pyproject.toml
- tutorials/self-host/aks/1-code/market_vendor/tests/sample_test.py
- tutorials/self-host/aks/1-code/readme.md
- tutorials/self-host/aks/2-build/Dockerfile
- tutorials/self-host/aks/2-build/SOPS_PUBLIC_KEYS
- tutorials/self-host/aks/2-build/readme.md
- tutorials/self-host/aks/3-test/market_vendor.ci.yaml
- tutorials/self-host/aks/3-test/readme.md
- tutorials/self-host/aks/4-release/readme.md
- tutorials/self-host/aks/5-deploy/dev.helmfile.yaml
- tutorials/self-host/aks/5-deploy/dev.values.yaml
- tutorials/self-host/aks/5-deploy/dockerize.template.yaml
- tutorials/self-host/aks/5-deploy/helm.template.yaml
- tutorials/self-host/aks/5-deploy/market_vendor.dev.cd.yaml
- tutorials/self-host/aks/5-deploy/readme.md
- tutorials/self-host/aks/6-operate/readme.md
- tutorials/self-host/aks/7-monitor/readme.md
- tutorials/self-host/aks/readme.md
This tutorial or mock files outline how assistants can be run side-by-side with the Unique workloads as we do on Customer Managed Tenants.
> feat(tutorials): add self-host/aks tutorial

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/content/test_content_service_unit.py
- unique_toolkit/unique_toolkit/content/utils.py
Refs: Na
Fix the mapping into the `ContentChunks` object to map into the correct columns as the assumption on which id's are what is incorrect
_Add screenshots, GIFs, or demo links to illustrate your changes._
Pytest library + monorepo
4. Merge PR
5. Run action **immediately** to publish to PyPI
> fix(ai): content search

- unique_sdk/CHANGELOG.md
- unique_sdk/README.md
- unique_sdk/pyproject.toml
- unique_sdk/unique_sdk/__init__.py
- unique_sdk/unique_sdk/api_resources/_space.py
- unique_sdk/unique_sdk/utils/chat_in_space.py
> feat(sdk): chat in space [UN-12332]

- unique_toolkit/CHANGELOG.md
- unique_toolkit/poetry.lock
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/app/test_unique_settings.py
- unique_toolkit/unique_toolkit/app/sse_client.py
- unique_toolkit/unique_toolkit/app/unique_settings.py
Fixed issue with UniqueSettings
> fix(ai): Fix issues and add tests to unique_settings

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/app/schemas.py
Refs: 
Attribute indicating tools disabled on a company level
Event is correctly received with latest version of unique platform
4. Merge PR
> feat(ai): new schema attribute

- unique_sdk/CHANGELOG.md
- unique_sdk/README.md
- unique_sdk/pyproject.toml
- unique_sdk/unique_sdk/api_resources/_search.py
- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
> feat(sdk): expose search threshold [UN-12667]

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/app/test_sse_client.py
- unique_toolkit/tests/app/test_unique_settings.py
- unique_toolkit/unique_toolkit/app/unique_settings.py
- unique_toolkit/unique_toolkit/framework_utilities/langchain/history.py
- unique_toolkit/unique_toolkit/framework_utilities/openai/client.py
Make unique settings object compatible with old environment variables
> feat(toolkit): Make unique settings compatilbe with legacy env variables

- unique_toolkit/CHANGELOG.md
- unique_toolkit/examples/frameworks/openai/chat_completion.py
- unique_toolkit/poetry.lock
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/chat/test_chat_service_unit.py
- unique_toolkit/unique_toolkit/app/__init__.py
- unique_toolkit/unique_toolkit/chat/functions.py
- unique_toolkit/unique_toolkit/chat/service.py
- unique_toolkit/unique_toolkit/framework_utilities/openai/message_builder.py
- unique_toolkit/unique_toolkit/language_model/builder.py
- unique_toolkit/unique_toolkit/language_model/functions.py
- unique_toolkit/unique_toolkit/language_model/schemas.py
Make the chat service compatible to the openai types so users can use the open ai message types instead of using `LanguageModelMessages`
> feat(toolkit): Make chat service openai compatible

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/language_model/test_language_model_functions_unit.py
- unique_toolkit/unique_toolkit/language_model/functions.py
- unique_toolkit/unique_toolkit/language_model/infos.py
> feat(ai-modules): Add temperature bounds and default options in LanguageModelInfo

- unique_sdk/CHANGELOG.md
- unique_sdk/README.md
- unique_sdk/pyproject.toml
- unique_sdk/unique_sdk/utils/chat_in_space.py
> feat(sdk): allow waiting for kb file ingestion

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/chat/schemas.py
- unique_toolkit/unique_toolkit/chat/service.py
- unique_toolkit/unique_toolkit/framework_utilities/openai/message_builder.py
> fix(toolkit): Fix chatmessage->openai message translation for toolcalls with empty lists

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/language_model/test_language_model_functions_integration.py
- unique_toolkit/tests/language_model/test_language_model_functions_unit.py
- unique_toolkit/tests/language_model/test_language_model_service_unit.py
- unique_toolkit/tests/language_model/test_language_models_service_unit.py
- unique_toolkit/unique_toolkit/language_model/functions.py
- unique_toolkit/unique_toolkit/language_model/service.py
…_async
Refs: [_link to or id of ticket_](https://unique-ch.atlassian.net/browse/UN-13109)
The function “complete_async” do not work and always returns “Unauthorized” error. It calls the function “create_async” which is, in order to work, needs the “user_id”.
---> Changes: Add “user_id” as argument to the “complete_async” function, and feed it to the “create_async” function
4. Merge PR
6. _Unique …
> fix(toolkit): add user_id argument to complete_async function

- unique_sdk/CHANGELOG.md
- unique_sdk/pyproject.toml
- unique_sdk/unique_sdk/__init__.py
- unique_sdk/unique_sdk/api_resources/_message_execution.py
- unique_sdk/unique_sdk/api_resources/_message_log.py
> feat(sdk): implement deep research apis [UN-13120]

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/evals/evaluation_manager.py
> fix(toolkit): Improved Evaluation manager

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/evals/evaluation_manager.py
- unique_toolkit/unique_toolkit/history_manager/history_manager.py
- unique_toolkit/unique_toolkit/tools/mcp/__init__.py
- unique_toolkit/unique_toolkit/tools/mcp/manager.py
- unique_toolkit/unique_toolkit/tools/mcp/models.py
- unique_toolkit/unique_toolkit/tools/mcp/tool_wrapper.py
- unique_toolkit/unique_toolkit/tools/schemas.py
- unique_toolkit/unique_toolkit/tools/tool.py
- unique_toolkit/unique_toolkit/tools/tool_manager.py
> fix(toolkit): Optimized MCP manager

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/language_model/functions.py
- unique_toolkit/unique_toolkit/language_model/service.py
- unique_toolkit/unique_toolkit/tools/mcp/manager.py
- unique_toolkit/unique_toolkit/tools/mcp/models.py
[Refs: _link to or id of ticket_
](https://unique-ch.atlassian.net/browse/UN-13109?atlOrigin=eyJpIjoiZmJiNWE0YThlYjg0NDZmZjgyYzgxNDk2YThhNTFhODYiLCJwIjoiaiJ9)
Briefly describe the changes introduced in this PR: 
- Make user_id optional in create_async to avoid breaking changes
- [ X] Added feature / fixed bug / updated docs
4. Merge PR
6. _Unique employees only: perform testing against monorepo and sync …
> fix(toolkit): make user_id optional in create_async

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/app/unique_settings.py
Fixes the `sdk_url` and the `openai_proxy_url` for localhost
> fix(toolkit): fix routing for localhost

- unique_sdk/CHANGELOG.md
- unique_sdk/pyproject.toml
- unique_sdk/unique_sdk/api_resources/_message_log.py
Refs: [_link to or id of ticket_](https://unique-ch.atlassian.net/browse/UN-13180)
4. Merge PR
> fix(sdk): add defaults for message log types

- .gitignore
- docs/index.md
- mkdocs.yaml
- unique_toolkit/CHANGELOG.md
- unique_toolkit/docs/index.md
- unique_toolkit/docs/setup/getting_started.md
- unique_toolkit/mkdocs.yaml
- unique_toolkit/pyproject.toml
Fix all links in the toolkit docs
> chore(toolkit): Ensure all links are working in documentation

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/framework_utilities/openai/__init__.py
- unique_toolkit/unique_toolkit/framework_utilities/openai/client.py
Introduce and async OpenAI Client generator
4. Merge PR
> feat(ai): async OpenAI client

- tool_packages/unique_internal_search/CHANGELOG.md
- tool_packages/unique_internal_search/pyproject.toml
- tool_packages/unique_internal_search/unique_internal_search/uploaded_search/config.py
- tool_packages/unique_internal_search/unique_internal_search/uploaded_search/prompts.py
- tool_packages/unique_internal_search/unique_internal_search/uploaded_search/service.py
- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/tools/a2a/service.py
> chore(internal-search): migrated uploaded search

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/app/unique_settings.py
Add alias for envs to allow for use in production Unique systems
4. Merge PR
> fix(ai): add the env alias

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/app/unique_settings.py
Missing identification of being used inside cluster
4. Merge PR
> fix(ai): identify call inside cluster

- tool_packages/unique_web_search/CHANGELOG.md
- tool_packages/unique_web_search/README.md
- tool_packages/unique_web_search/pyproject.toml
Refs: UN-13362
Updated unique_web_search README
4. Merge PR
> fix(ai-modules): update unique web search readme

- tool_packages/unique_internal_search/CHANGELOG.md
- tool_packages/unique_internal_search/pyproject.toml
- tool_packages/unique_internal_search/unique_internal_search/service.py
> fix(internal-search): Deepcopy removed as it is not needed

- unique_sdk/CHANGELOG.md
- unique_sdk/README.md
- unique_sdk/pyproject.toml
- unique_sdk/unique_sdk/api_resources/_chat_completion.py
> chore(sdk): revert chat completions reasoning effort typing

- tool_packages/unique_web_search/CHANGELOG.md
- tool_packages/unique_web_search/pyproject.toml
- tool_packages/unique_web_search/unique_web_search/services/content_processing/service.py
> feat(websearch): Add back content utf-8 normalization

- unique_orchestrator/pyproject.toml
> fix: Update Orchestrator

- unique_orchestrator/CHANGELOG.md
- unique_orchestrator/pyproject.toml
- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/agentic/tools/config.py
- [x ] Added feature / fixed bug / updated docs
> fix(toolkit): Added icon names

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/agentic/tools/test/test_mcp_manager.py
- unique_toolkit/unique_toolkit/agentic/tools/tool_manager.py
> fix(toolkit): Fixed exclusive tool selection

- unique_sdk/CHANGELOG.md
- unique_sdk/README.md
- unique_sdk/pyproject.toml
> chore(sdk): use unique ai

- unique_orchestrator/CHANGELOG.md
- unique_orchestrator/README.md
- unique_orchestrator/pyproject.toml
- unique_orchestrator/unique_orchestrator/prompts/system_prompt.jinja2
> fix(uai): UAI systemp prompt for not activated tools, version bump

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/app/dev_util.py
- unique_toolkit/unique_toolkit/app/unique_settings.py
The event generator automatically updates settings such as `user_id` and `company_id` from the received event
> feat(toolkit): Autoupdate settings from event stream

- tool_packages/unique_web_search/CHANGELOG.md
- tool_packages/unique_web_search/poetry.lock
- tool_packages/unique_web_search/pyproject.toml
- tool_packages/unique_web_search/unique_web_search/config.py
- tool_packages/unique_web_search/unique_web_search/services/content_processing/service.py
- tool_packages/unique_web_search/unique_web_search/services/crawlers/base.py
- tool_packages/unique_web_search/unique_web_search/services/crawlers/firecrawl.py
- tool_packages/unique_web_search/unique_web_search/services/crawlers/jina.py
- tool_packages/unique_web_search/unique_web_search/services/crawlers/tavily.py
- tool_packages/unique_web_search/unique_web_search/services/helpers.py
- tool_packages/unique_web_search/unique_web_search/services/search_engine/__init__.py
- tool_packages/unique_web_search/unique_web_search/services/search_engine/base.py
add experimental flag to new crawlers
Tested locally
> fix: Add experimental flag to new crawlers

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/agentic/tools/a2a/evaluation/evaluator.py
Handle failed assessments more robustly in sub-agent evaluator
> fix(toolkit): Handle failed assessments more robustly in sub-agent evaluator

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/tests/language_model/test_language_model_infos.py
- unique_toolkit/unique_toolkit/language_model/infos.py
> feat(ai): adding new antropic models to model info

- tool_packages/unique_deep_research/CHANGELOG.md
- tool_packages/unique_deep_research/pyproject.toml
- tool_packages/unique_deep_research/unique_deep_research/service.py
- tool_packages/unique_deep_research/unique_deep_research/templates/unique/compress_research_system.j2
- tool_packages/unique_deep_research/unique_deep_research/templates/unique/lead_agent_system.j2
- tool_packages/unique_deep_research/unique_deep_research/templates/unique/report_writer_system_open_deep_research.j2
- tool_packages/unique_deep_research/unique_deep_research/templates/unique/research_agent_system.j2
- tool_packages/unique_deep_research/unique_deep_research/unique_custom/agents.py
- tool_packages/unique_deep_research/unique_deep_research/unique_custom/tools.py
- Prompt improvements
- research complete tool for subagents
> feat(ai): prompt improvements

- tool_packages/unique_deep_research/CHANGELOG.md
- tool_packages/unique_deep_research/pyproject.toml
- tool_packages/unique_deep_research/unique_deep_research/templates/openai/report_postprocessing_system.j2
- tool_packages/unique_deep_research/unique_deep_research/unique_custom/agents.py
- tool_packages/unique_deep_research/unique_deep_research/unique_custom/tools.py
- bugfix of langgraph state issue
- more logging
> fix(ai): langraph state routing issue

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/agentic/tools/a2a/__init__.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/config.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/evaluation/__init__.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/evaluation/_utils.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/evaluation/config.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/evaluation/evaluator.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/manager.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/postprocessing/__init__.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/postprocessing/_display.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/postprocessing/_utils.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/postprocessing/config.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/postprocessing/postprocessor.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/postprocessing/test/test_consolidate_references.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/postprocessing/test/test_display.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/postprocessing/test/test_postprocessor_reference_functions.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/tool/__init__.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/tool/_memory.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/tool/_schema.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/tool/config.py
- unique_toolkit/unique_toolkit/agentic/tools/a2a/tool/service.py
- unique_toolkit/unique_toolkit/agentic/tools/config.py
- unique_toolkit/unique_toolkit/agentic/tools/tool_manager.py
feat(toolkit): Refactor and test new sub agent features
> feat(toolkit): Refactor and test new sub agent features

- unique_orchestrator/CHANGELOG.md
- unique_orchestrator/poetry.lock
- unique_orchestrator/pyproject.toml
- unique_orchestrator/unique_orchestrator/config.py
- unique_orchestrator/unique_orchestrator/unique_ai_builder.py
Adapt orchestrator to sub agent's refactoring
> chore(orchestrator): Adapt orchestrator to sub agents feature refactoring

- postprocessors/unique_stock_ticker/README.md
> chore(ai): adding missing readme for stock-ticker

- unique_orchestrator/CHANGELOG.md
- unique_orchestrator/poetry.lock
- unique_orchestrator/pyproject.toml
- unique_orchestrator/unique_orchestrator/config.py
- unique_orchestrator/unique_orchestrator/prompts/system_prompt.jinja2
- unique_orchestrator/unique_orchestrator/prompts/user_message_prompt.jinja2
- unique_orchestrator/unique_orchestrator/unique_ai.py
Implement changes necessary for sub-agent response referencing in the orchestrator.
> feat(orchestrator): Implement sub-agent response referencing

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/content/functions.py
- unique_toolkit/unique_toolkit/content/schemas.py
- unique_toolkit/unique_toolkit/knowledge_base.py
> fix(toolkit): Empty metadatafilter at info retrieval

- tool_packages/unique_deep_research/CHANGELOG.md
- tool_packages/unique_deep_research/pyproject.toml
- tool_packages/unique_deep_research/unique_deep_research/config.py
- tool_packages/unique_deep_research/unique_deep_research/service.py
- tool_packages/unique_deep_research/unique_deep_research/templates/report_cleanup_prompt.j2
- tool_packages/unique_deep_research/unique_deep_research/templates/unique/lead_agent_system.j2
- tool_packages/unique_deep_research/unique_deep_research/templates/unique/report_writer_system_open_deep_research.j2
- tool_packages/unique_deep_research/unique_deep_research/templates/unique/research_agent_system.j2
- tool_packages/unique_deep_research/unique_deep_research/unique_custom/agents.py
- tool_packages/unique_deep_research/unique_deep_research/unique_custom/utils.py
Refs: https://unique-ch.atlassian.net/browse/UN-13917
Simplify the configuration setup and better default values for rendering
> feat(ai): simplify config from user rendered perspective and prompt improvements

- docs/index.md
- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/test_utilities/events.py
> feat(toolkit): Add utility class to generate events for tests

- unique_toolkit/CHANGELOG.md
- unique_toolkit/pyproject.toml
- unique_toolkit/unique_toolkit/test_utilities/events.py
> fix(toolkit): Fix import issue
